import {  Josefin_Sans, Gabarito } from "next/font/google";
import "./globals.css";


const josefinSans = Josefin_Sans({
      subsets: ['latin'], 
      display: 'swap', 
      variable: '--font-josefin-sans', 
    });

const gabarito = Gabarito({
      subsets: ['latin'], 
      display: 'swap', 
      variable: '--font-gabarito',
    });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${josefinSans.variable} ${gabarito.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
