'use client'
import { Josefin_Sans, Gabarito } from "next/font/google";
import "../globals.css";
import Sidebar from "@/components/layout/Sidebar";
import { useState } from "react";
import { IoIosArrowForward } from "react-icons/io";
import Image from "node_modules/next/image";
import user from '@/assets/images/user.png'
import { CiSearch } from "react-icons/ci";
import { IoNotificationsCircle } from "react-icons/io5";
import chatbotIcon from '@/assets/icons/chatbot.svg'
import Link from "node_modules/next/link";

const josefinSans = Josefin_Sans({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-josefin-sans',
});

const gabarito = Gabarito({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-gabarito',
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

    const [open, setOpen] = useState(false);

    const showDrawer = () => {
        setOpen(true);
    };
    const closeDrawer = () => {
        setOpen(false);
    };

    return (
        <html lang="en">
            <body
                className={`${josefinSans.variable} ${gabarito.variable} antialiased`}
            >
                <div className='flex items-center pt-4 lg:pt-10  md:px-6 lg:px-6 xl:px-16'>
                    {/* small device arrow button */}
                    <div className="text-2xl pl-2 lg:hidden">
                        <button onClick={showDrawer} className="cursor-pointer"><IoIosArrowForward /></button>
                    </div>

                   <div className="flex justify-between w-full">
                     {/* user */}
                    <div className='flex items-center gap-2'>
                        <Link href="/settings">
                        <Image src={user} alt='user' className='w-14 lg:w-20 rounded-full' />
                        </Link>
                        <div className='lg:space-y-2'>
                            <h2 className='font-josefin-sans font-semibold text-xl lg:text-2xl'>Good Morning Alex!</h2>
                            <p className='font-josefin-sans font-medium text-gray-500  lg:text-xl'>Track your health with Bootble</p>
                        </div>
                    </div>

                    {/* search + notofication icons */}
                    <div className="flex gap-1 items-center">
                        {/* search */}
                        {/* <div className="bg-white w-10 h-10 flex items-center justify-center rounded-full text-xl ">
                            <CiSearch />
                        </div> */}

                        {/* notification */}
                        <div>
                            <Link href="/notifications">
                            <IoNotificationsCircle className='w-12 h-12'/>
                            </Link>
                        </div>
                    </div>

                   </div>

                    
                </div>


                <div className=" flex flex-col md:flex-row lg:gap-10 2xl:gap-20 px-4 md:px-10 lg:px-6 xl:px-16 pt-10 pb-4 ">
                    <Sidebar open={open} onClose={closeDrawer} />

                    <main className=" flex-1">{children}</main>

                    {/* chatbot Icon */}
                    <div className="flex items-end">
                    <Link href="/chat-with-your-assistant">
                    <Image src={chatbotIcon} alt="icon" />
                    </Link>
                </div>
                </div>

                
            </body>
        </html>
    );
}
